### ISSUE TITLE
ValueError: not enough frames were found that at least 100.0% of the markers.

### ISSUE THREAD

**Issue by yufu-liu** [nghorbani/soma#27]
Hi, thanks for this amazing work again!

When I tried to use my MoCap data as input to "solve_labeled_mocap.ipynb", this error appeared.
However, it didn't happen for every MoCap file, so I guess it was caused by the input data.
Just wonder if there is way to solve it or ignore it?

The whole error description:
**ValueError: not enough frames were found that at least 100.0% of the markers.
either try mosh.stagei_frame_picker.type: random or set mosh.stagei.frame.picker.least_avail_markers to lower number in ange [0.1, 1.0]**

**Comment by yufu-liu** [comment]
After changing stagei_frame_picker type to random in mosh_conf.yaml, error doesn't show up again.

**Comment by GaigeY** [comment]
Hi. I have met the same problem while runing the tutorial, and I want to share my experience to solve this issue.

This issue is caused by the **wrong point labels** in mpc data, which should be offered in your `.c3d` files. If you use other mocap data instead of `SOMA_manual_labeled` mocap data, and some point labels in your data are not supported by MoSh++ layout marker setting, some issues would be raised.
Anyway, if you use AMASS data (with supported marker labels) to run the tutorial, changing `stagei_frame_picker` as `random` might be OK.
